/**
 * Default bankKeywordRules seed data.
 *
 * Source of truth:
 * `.planning/phases/72-bank-statement-parser-auto-match/72-SEED-RULES.json`
 *
 * The rule set encodes 26 canonical Indonesian bank-statement classification
 * rules captured from the real BCA data (CONTEXT.md D-16 / D-17). Account refs
 * are LOGICAL names — the seed mutation resolves each to an `accounts._id`
 * (by `accounts.name`). Unresolved refs fail the seed loudly.
 *
 * Rule code conventions (matches `/^[A-Z]\d{2}$/`):
 *   R01-R12 → Revenue
 *   C01-C03 → COGS
 *   O01-O09 → OpEx
 *   B01-B02 → Below-the-line (CapEx, owner draws)
 *
 * Precedence tiers (see SEED-RULES.json §metadata.precedenceTiers):
 *   100: named personal/entity counterparties (R11, R12, B02)
 *   80:  platform counterparties (R02..R07)
 *   60:  description + counterparty (C01, C02, C03, O01, O03, O04, O06, O07, B01)
 *   40:  description + direction (O02, O05, O08, O09, R08, R09, R10)
 *   20:  catch-all default — R01 ONLY (isCatchAll=true)
 *
 * IMPORTANT: R01 is the ONE and ONLY catch-all. The match engine splits
 * catch-all rules from the rest BEFORE sorting (T-72-14 mitigation). Adding a
 * second catch-all here would silently break the classifier; the seed tests
 * pin this invariant.
 */

// ---------------------------------------------------------------------------
// Account ref map — 20 logical account refs → accounts.name to resolve at seed time
// ---------------------------------------------------------------------------

export const DEFAULT_ACCOUNT_REFS: ReadonlyArray<{ ref: string; accountName: string }> = [
  { ref: "cash-bca-main", accountName: "Cash / Bank — BCA Main" },
  { ref: "revenue-direct-sales", accountName: "Revenue — Direct Sales / Transfers" },
  { ref: "revenue-gopay-gofood", accountName: "Revenue — GoPay / GoFood" },
  { ref: "revenue-ovo-shopeepay", accountName: "Revenue — OVO / ShopeePay" },
  { ref: "revenue-marketplace-tokopedia", accountName: "Revenue — Marketplace Payouts (Tokopedia)" },
  { ref: "revenue-marketplace-shopee", accountName: "Revenue — Marketplace Payouts (Shopee / AirPay)" },
  { ref: "revenue-cafe-ruma52", accountName: "Revenue — Cafe Wholesale (Ruma 52)" },
  { ref: "revenue-cafe-thirdhome", accountName: "Revenue — Cafe Wholesale (Thirdhome)" },
  { ref: "revenue-refunds-contra", accountName: "Revenue — Customer Refunds (contra-revenue)" },
  { ref: "cogs-raw-materials", accountName: "COGS — Raw Materials & Ingredients" },
  { ref: "cogs-packaging", accountName: "COGS — Packaging" },
  { ref: "cogs-production-labor", accountName: "COGS — Production Labor (Contractor)" },
  { ref: "opex-payroll-wages", accountName: "OpEx — Payroll & Wages" },
  { ref: "opex-delivery-logistics", accountName: "OpEx — Delivery & Logistics" },
  { ref: "opex-marketing-printing", accountName: "OpEx — Marketing & Printing" },
  { ref: "opex-ecommerce-supplies", accountName: "OpEx — E-commerce / Marketplace Supplies" },
  { ref: "opex-legal-licensing", accountName: "OpEx — Legal & Licensing" },
  { ref: "opex-rnd-misc", accountName: "OpEx — R&D / Telecom / Office / Bank Fees" },
  { ref: "fixedAssets-equipment", accountName: "Fixed Assets — Equipment & Machinery" },
  { ref: "equity-owner-drawing", accountName: "Equity — Owner Drawing / Related-Party Receivable" },
];

// ---------------------------------------------------------------------------
// Default rules — 26 entries. Every literal field is narrowed to match schema unions.
// ---------------------------------------------------------------------------

export type DefaultRule = {
  ruleCode: string;
  plSection: "Revenue" | "COGS" | "OpEx" | "Below the Line";
  categoryRef: string;
  subCategoryTemplate?: string;
  direction: "debit" | "credit" | "any";
  matchType:
    | "counterparty"
    | "description_contains"
    | "description_exact"
    | "description_regex"
    | "counterparty_or_keyword"
    | "counterparty_and_keyword"
    | "catch_all";
  counterpartyPatterns?: string[];
  descriptionPatterns?: string[];
  descriptionPatternsMode: "any" | "all" | "hint";
  isCatchAll: boolean;
  jeDebitRef: string;
  jeCreditRef: string;
  linkedChannel?: string;
  confidence: "exact" | "strong" | "suggested";
  priority: number;
  flags?: string[];
  isActive: boolean;
};

export const DEFAULT_RULES: ReadonlyArray<DefaultRule> = [
  // ---- Revenue rules ----
  {
    ruleCode: "R01",
    plSection: "Revenue",
    categoryRef: "revenue-direct-sales",
    subCategoryTemplate: "Direct Bank Transfer Order",
    direction: "credit",
    matchType: "catch_all",
    descriptionPatterns: ["dubai", "frollie", "chewy"],
    descriptionPatternsMode: "hint",
    isCatchAll: true,
    jeDebitRef: "cash-bca-main",
    jeCreditRef: "revenue-direct-sales",
    linkedChannel: "direct",
    confidence: "suggested",
    priority: 20,
    isActive: true,
  },
  {
    ruleCode: "R02",
    plSection: "Revenue",
    categoryRef: "revenue-gopay-gofood",
    subCategoryTemplate: "GoPay / GoFood Settlement",
    direction: "credit",
    matchType: "counterparty",
    counterpartyPatterns: ["DOMPET ANAK BANGSA"],
    descriptionPatterns: ["G293156297", "G347061572", "G958262444", "WLST"],
    descriptionPatternsMode: "hint",
    isCatchAll: false,
    jeDebitRef: "cash-bca-main",
    jeCreditRef: "revenue-gopay-gofood",
    linkedChannel: "gopay",
    confidence: "exact",
    priority: 80,
    isActive: true,
  },
  {
    ruleCode: "R03",
    plSection: "Revenue",
    categoryRef: "revenue-ovo-shopeepay",
    subCategoryTemplate: "OVO / ShopeePay Settlement",
    direction: "credit",
    matchType: "counterparty",
    counterpartyPatterns: ["VISIONET INTERNASI"],
    descriptionPatterns: ["6044830994"],
    descriptionPatternsMode: "hint",
    isCatchAll: false,
    jeDebitRef: "cash-bca-main",
    jeCreditRef: "revenue-ovo-shopeepay",
    linkedChannel: "ovo",
    confidence: "exact",
    priority: 80,
    isActive: true,
  },
  {
    ruleCode: "R04",
    plSection: "Revenue",
    categoryRef: "revenue-marketplace-tokopedia",
    subCategoryTemplate: "Tokopedia Marketplace Payout",
    direction: "credit",
    matchType: "counterparty",
    counterpartyPatterns: ["TOKOPEDIA PT"],
    descriptionPatterns: ["WD", "TKPD"],
    descriptionPatternsMode: "hint",
    isCatchAll: false,
    jeDebitRef: "cash-bca-main",
    jeCreditRef: "revenue-marketplace-tokopedia",
    linkedChannel: "tokopedia",
    confidence: "exact",
    priority: 80,
    isActive: true,
  },
  {
    ruleCode: "R05",
    plSection: "Revenue",
    categoryRef: "revenue-marketplace-shopee",
    subCategoryTemplate: "Shopee Marketplace Payout (via AirPay)",
    direction: "credit",
    matchType: "counterparty",
    counterpartyPatterns: ["AIRPAY INTERNATION"],
    descriptionPatterns: ["200008203"],
    descriptionPatternsMode: "hint",
    isCatchAll: false,
    jeDebitRef: "cash-bca-main",
    jeCreditRef: "revenue-marketplace-shopee",
    linkedChannel: "shopee",
    confidence: "exact",
    priority: 80,
    isActive: true,
  },
  {
    ruleCode: "R06",
    plSection: "Revenue",
    categoryRef: "revenue-marketplace-tokopedia",
    subCategoryTemplate: "Katiga Ritel Settlement",
    direction: "credit",
    matchType: "counterparty",
    counterpartyPatterns: ["KATIGA RITEL STREN"],
    descriptionPatterns: ["ATSCY", "REF:"],
    descriptionPatternsMode: "hint",
    isCatchAll: false,
    jeDebitRef: "cash-bca-main",
    jeCreditRef: "revenue-marketplace-tokopedia",
    linkedChannel: "katiga",
    confidence: "exact",
    priority: 80,
    isActive: true,
  },
  {
    ruleCode: "R07",
    plSection: "Revenue",
    categoryRef: "revenue-direct-sales",
    subCategoryTemplate: "Skala Pangan B2B Order",
    direction: "credit",
    matchType: "counterparty",
    counterpartyPatterns: ["SKALA PANGAN INDON"],
    descriptionPatterns: ["Frollie", "Rev shar frollie"],
    descriptionPatternsMode: "hint",
    isCatchAll: false,
    jeDebitRef: "cash-bca-main",
    jeCreditRef: "revenue-direct-sales",
    linkedChannel: "direct",
    confidence: "exact",
    priority: 80,
    isActive: true,
  },
  {
    ruleCode: "R08",
    plSection: "Revenue",
    categoryRef: "revenue-direct-sales",
    subCategoryTemplate: "Auto Standing Order Customer Payment",
    direction: "credit",
    matchType: "description_contains",
    descriptionPatterns: ["KR OTOMATIS NTRF@", "AFR"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "cash-bca-main",
    jeCreditRef: "revenue-direct-sales",
    linkedChannel: "direct",
    confidence: "strong",
    priority: 40,
    isActive: true,
  },
  {
    ruleCode: "R09",
    plSection: "Revenue",
    categoryRef: "revenue-direct-sales",
    subCategoryTemplate: "BI-FAST Interbank Customer Credit",
    direction: "credit",
    matchType: "description_contains",
    descriptionPatterns: ["BI-FAST CR TRANSFER"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "cash-bca-main",
    jeCreditRef: "revenue-direct-sales",
    linkedChannel: "direct",
    confidence: "strong",
    priority: 40,
    isActive: true,
  },
  {
    ruleCode: "R10",
    plSection: "Revenue",
    categoryRef: "revenue-refunds-contra",
    subCategoryTemplate: "Customer Refund / Shipping Correction",
    direction: "debit",
    matchType: "description_contains",
    descriptionPatterns: ["refund", "Refund ongkir", "Refund Ship error"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "revenue-refunds-contra",
    jeCreditRef: "cash-bca-main",
    confidence: "strong",
    priority: 40,
    flags: ["negates_revenue"],
    isActive: true,
  },
  {
    ruleCode: "R11",
    plSection: "Revenue",
    categoryRef: "revenue-cafe-ruma52",
    subCategoryTemplate: "Ruma 52 Cafe Wholesale Order",
    direction: "credit",
    matchType: "counterparty",
    counterpartyPatterns: ["CLARITA RAQUEL AMA"],
    descriptionPatterns: ["Ruma 52", "ruma52", "Frollie ruma 52"],
    descriptionPatternsMode: "hint",
    isCatchAll: false,
    jeDebitRef: "cash-bca-main",
    jeCreditRef: "revenue-cafe-ruma52",
    linkedChannel: "cafe_ruma52",
    confidence: "exact",
    priority: 100,
    isActive: true,
  },
  {
    ruleCode: "R12",
    plSection: "Revenue",
    categoryRef: "revenue-cafe-thirdhome",
    subCategoryTemplate: "Thirdhome Cafe Wholesale Order",
    direction: "credit",
    matchType: "counterparty",
    counterpartyPatterns: ["NIDIA O L ATAU ELI"],
    descriptionPatterns: ["Thirdhome", "Chewy"],
    descriptionPatternsMode: "hint",
    isCatchAll: false,
    jeDebitRef: "cash-bca-main",
    jeCreditRef: "revenue-cafe-thirdhome",
    linkedChannel: "cafe_thirdhome",
    confidence: "exact",
    priority: 100,
    isActive: true,
  },

  // ---- COGS rules ----
  {
    ruleCode: "C01",
    plSection: "COGS",
    categoryRef: "cogs-raw-materials",
    subCategoryTemplate: "Raw Materials / Ingredients / Moulds",
    direction: "debit",
    matchType: "counterparty_or_keyword",
    counterpartyPatterns: ["KEVIN YOSUA", "RASA BOGA SEJATI", "FLIPTECH LENTERA"],
    descriptionPatterns: ["ingredients", "marshmallow", "credotti", "Corn kernels", "Sillicone mat", "Mochi Mold"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "cogs-raw-materials",
    jeCreditRef: "cash-bca-main",
    confidence: "strong",
    priority: 60,
    isActive: true,
  },
  {
    ruleCode: "C02",
    plSection: "COGS",
    categoryRef: "cogs-packaging",
    subCategoryTemplate: "Packaging Materials",
    direction: "debit",
    matchType: "counterparty_or_keyword",
    counterpartyPatterns: ["NIU ULUNG", "NILSON TANDIONO"],
    descriptionPatterns: ["packaging", "plastic bag", "Stickers", "Mochi Packaging"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "cogs-packaging",
    jeCreditRef: "cash-bca-main",
    confidence: "strong",
    priority: 60,
    isActive: true,
  },
  {
    ruleCode: "C03",
    plSection: "COGS",
    categoryRef: "cogs-production-labor",
    subCategoryTemplate: "Production Contractor Fee",
    direction: "debit",
    matchType: "counterparty_and_keyword",
    counterpartyPatterns: ["PIERRE KEVIN ANGEL"],
    descriptionPatterns: ["Fee Pierre", "Produksi", "Porudksi"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "cogs-production-labor",
    jeCreditRef: "cash-bca-main",
    confidence: "strong",
    priority: 60,
    isActive: true,
  },

  // ---- OpEx rules ----
  {
    ruleCode: "O01",
    plSection: "OpEx",
    categoryRef: "opex-payroll-wages",
    subCategoryTemplate: "Employee Salary — Madelynne",
    direction: "debit",
    matchType: "counterparty_or_keyword",
    counterpartyPatterns: ["MADELYNNE"],
    descriptionPatterns: ["salary", "mei2 salary"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "opex-payroll-wages",
    jeCreditRef: "cash-bca-main",
    confidence: "strong",
    priority: 60,
    isActive: true,
  },
  {
    ruleCode: "O02",
    plSection: "OpEx",
    categoryRef: "opex-delivery-logistics",
    subCategoryTemplate: "Shipping & Delivery (Outbound)",
    direction: "debit",
    matchType: "counterparty_and_keyword",
    counterpartyPatterns: ["PIERRE KEVIN ANGEL", "NILSON TANDIONO"],
    descriptionPatterns: ["Shipping", "Transport", "ongkir", "Ongkir chewy", "deliv"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "opex-delivery-logistics",
    jeCreditRef: "cash-bca-main",
    confidence: "strong",
    priority: 40,
    isActive: true,
  },
  {
    ruleCode: "O03",
    plSection: "OpEx",
    categoryRef: "opex-delivery-logistics",
    subCategoryTemplate: "LalaMove Delivery",
    direction: "debit",
    matchType: "description_contains",
    descriptionPatterns: ["/LALAMOVE"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "opex-delivery-logistics",
    jeCreditRef: "cash-bca-main",
    confidence: "exact",
    priority: 60,
    isActive: true,
  },
  {
    ruleCode: "O04",
    plSection: "OpEx",
    categoryRef: "opex-delivery-logistics",
    subCategoryTemplate: "OVO Top-up (used for LalaMove)",
    direction: "debit",
    matchType: "description_contains",
    descriptionPatterns: ["/OVO"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "opex-delivery-logistics",
    jeCreditRef: "cash-bca-main",
    confidence: "exact",
    priority: 60,
    flags: ["direction_sensitive"],
    isActive: true,
  },
  {
    ruleCode: "O05",
    plSection: "OpEx",
    categoryRef: "opex-marketing-printing",
    subCategoryTemplate: "Printing / Labels / Marketing",
    direction: "debit",
    matchType: "counterparty_and_keyword",
    counterpartyPatterns: ["PILAR PRATAMA MAND", "CV JOSS PRINT", "RASA BOGA SEJATI C"],
    descriptionPatterns: ["Printing", "Sticker"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "opex-marketing-printing",
    jeCreditRef: "cash-bca-main",
    confidence: "strong",
    priority: 40,
    isActive: true,
  },
  {
    ruleCode: "O06",
    plSection: "OpEx",
    categoryRef: "opex-ecommerce-supplies",
    subCategoryTemplate: "Shopee Purchase (Supplies / Fees)",
    direction: "debit",
    matchType: "description_contains",
    descriptionPatterns: ["/SHOPEE", "12608"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "opex-ecommerce-supplies",
    jeCreditRef: "cash-bca-main",
    confidence: "suggested",
    priority: 60,
    flags: ["needs_line_item_review", "direction_sensitive"],
    isActive: true,
  },
  {
    ruleCode: "O07",
    plSection: "OpEx",
    categoryRef: "opex-ecommerce-supplies",
    subCategoryTemplate: "Tokopedia Purchase (Supplies / Fees)",
    direction: "debit",
    matchType: "description_contains",
    descriptionPatterns: ["/TOKOPEDIA", "80777"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "opex-ecommerce-supplies",
    jeCreditRef: "cash-bca-main",
    confidence: "suggested",
    priority: 60,
    flags: ["needs_line_item_review", "direction_sensitive"],
    isActive: true,
  },
  {
    ruleCode: "O08",
    plSection: "OpEx",
    categoryRef: "opex-legal-licensing",
    subCategoryTemplate: "Trademark / Patent Registration",
    direction: "debit",
    matchType: "counterparty_and_keyword",
    counterpartyPatterns: ["DEBORA FEBRIANTI H"],
    descriptionPatterns: ["Name paten", "paten"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "opex-legal-licensing",
    jeCreditRef: "cash-bca-main",
    confidence: "strong",
    priority: 40,
    isActive: true,
  },
  {
    ruleCode: "O09",
    plSection: "OpEx",
    categoryRef: "opex-rnd-misc",
    subCategoryTemplate: "R&D / Office / Telecom / Bank Fees (Misc)",
    direction: "debit",
    matchType: "description_contains",
    descriptionPatterns: ["R&D", "Stationary", "Gloves", "BY.U", "BIAYA ADM", "BIAYA TXN"],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "opex-rnd-misc",
    jeCreditRef: "cash-bca-main",
    confidence: "strong",
    priority: 40,
    flags: ["catch_all_misc"],
    isActive: true,
  },

  // ---- Below-the-line rules ----
  {
    ruleCode: "B01",
    plSection: "Below the Line",
    categoryRef: "fixedAssets-equipment",
    subCategoryTemplate: "CapEx — Equipment / Machinery",
    direction: "debit",
    matchType: "description_contains",
    descriptionPatterns: [
      "mesin",
      "machine",
      "Setup Machine",
      "extruder",
      "coat machine",
      "service mesin",
      "Scale",
      "Hand Held printer",
      "Asset Teflon",
    ],
    descriptionPatternsMode: "any",
    isCatchAll: false,
    jeDebitRef: "fixedAssets-equipment",
    jeCreditRef: "cash-bca-main",
    confidence: "strong",
    priority: 60,
    flags: ["capex_needs_asset_register"],
    isActive: true,
  },
  {
    ruleCode: "B02",
    plSection: "Below the Line",
    categoryRef: "equity-owner-drawing",
    subCategoryTemplate: "Owner Draw / Related-Party Transfer",
    direction: "debit",
    matchType: "counterparty",
    counterpartyPatterns: ["TANIA JOCELYNN TRI", "NATASHA TAMARANI", "RISTIANA ETENG"],
    descriptionPatterns: ["BI-FAST DB TRANSFER", "KBB"],
    descriptionPatternsMode: "hint",
    isCatchAll: false,
    jeDebitRef: "equity-owner-drawing",
    jeCreditRef: "cash-bca-main",
    confidence: "exact",
    priority: 100,
    flags: ["related_party"],
    isActive: true,
  },
];
