/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as accounts_mutations from "../accounts/mutations.js";
import type * as accounts_queries from "../accounts/queries.js";
import type * as auth_mutations from "../auth/mutations.js";
import type * as auth_queries from "../auth/queries.js";
import type * as auth_seed from "../auth/seed.js";
import type * as bankAccounts_mutations from "../bankAccounts/mutations.js";
import type * as bankAccounts_queries from "../bankAccounts/queries.js";
import type * as bankKeywordRules_defaultRules from "../bankKeywordRules/defaultRules.js";
import type * as bankKeywordRules_mutations from "../bankKeywordRules/mutations.js";
import type * as bankKeywordRules_queries from "../bankKeywordRules/queries.js";
import type * as bankStatements___tests___reconcileHelpers from "../bankStatements/__tests__/reconcileHelpers.js";
import type * as bankStatements_channelMapping from "../bankStatements/channelMapping.js";
import type * as bankStatements_matchEngine from "../bankStatements/matchEngine.js";
import type * as bankStatements_mutations from "../bankStatements/mutations.js";
import type * as bankStatements_queries from "../bankStatements/queries.js";
import type * as bigsellerOrders_actions from "../bigsellerOrders/actions.js";
import type * as bigsellerOrders_mutations from "../bigsellerOrders/mutations.js";
import type * as bigsellerOrders_queries from "../bigsellerOrders/queries.js";
import type * as businessSettings_mutations from "../businessSettings/mutations.js";
import type * as businessSettings_queries from "../businessSettings/queries.js";
import type * as channels_mutations from "../channels/mutations.js";
import type * as channels_queries from "../channels/queries.js";
import type * as componentTypes_dedupe from "../componentTypes/dedupe.js";
import type * as componentTypes_helpers from "../componentTypes/helpers.js";
import type * as componentTypes_mutations from "../componentTypes/mutations.js";
import type * as componentTypes_queries from "../componentTypes/queries.js";
import type * as componentTypes_seed from "../componentTypes/seed.js";
import type * as consignment_helpers from "../consignment/helpers.js";
import type * as consignment_mutations from "../consignment/mutations.js";
import type * as consignment_queries from "../consignment/queries.js";
import type * as crons from "../crons.js";
import type * as customers_mutations from "../customers/mutations.js";
import type * as customers_queries from "../customers/queries.js";
import type * as dispatchPlanner_helpers from "../dispatchPlanner/helpers.js";
import type * as dispatchPlanner_helpers_index from "../dispatchPlanner/helpers/index.js";
import type * as dispatchPlanner_helpers_inventorySimulation from "../dispatchPlanner/helpers/inventorySimulation.js";
import type * as dispatchPlanner_helpers_weeklyPlanBuilder from "../dispatchPlanner/helpers/weeklyPlanBuilder.js";
import type * as dispatchPlanner_mutations from "../dispatchPlanner/mutations.js";
import type * as dispatchPlanner_queries from "../dispatchPlanner/queries.js";
import type * as dispatchPlanner_types from "../dispatchPlanner/types.js";
import type * as expenses_analyticsQueries from "../expenses/analyticsQueries.js";
import type * as expenses_auditTrail from "../expenses/auditTrail.js";
import type * as expenses_bulkMutations from "../expenses/bulkMutations.js";
import type * as expenses_constants from "../expenses/constants.js";
import type * as expenses_fraudHelpers from "../expenses/fraudHelpers.js";
import type * as expenses_helpers from "../expenses/helpers.js";
import type * as expenses_mutations from "../expenses/mutations.js";
import type * as expenses_queries from "../expenses/queries.js";
import type * as externalData_actions from "../externalData/actions.js";
import type * as externalData_helpers_dashboardHelpers from "../externalData/helpers/dashboardHelpers.js";
import type * as externalData_helpers_lifetimeHelpers from "../externalData/helpers/lifetimeHelpers.js";
import type * as externalData_helpers_restockHelpers from "../externalData/helpers/restockHelpers.js";
import type * as externalData_helpers_revenueItemsHelpers from "../externalData/helpers/revenueItemsHelpers.js";
import type * as externalData_helpers_sellThroughHelpers from "../externalData/helpers/sellThroughHelpers.js";
import type * as externalData_helpers_timeSeriesHelpers from "../externalData/helpers/timeSeriesHelpers.js";
import type * as externalData_mutations from "../externalData/mutations.js";
import type * as externalData_queries from "../externalData/queries.js";
import type * as feedback_mutations from "../feedback/mutations.js";
import type * as feedback_queries from "../feedback/queries.js";
import type * as fixedAssets_helpers from "../fixedAssets/helpers.js";
import type * as fixedAssets_mutations from "../fixedAssets/mutations.js";
import type * as fixedAssets_queries from "../fixedAssets/queries.js";
import type * as gofoodDepot_helpers from "../gofoodDepot/helpers.js";
import type * as gofoodDepot_mutations from "../gofoodDepot/mutations.js";
import type * as gofoodDepot_queries from "../gofoodDepot/queries.js";
import type * as grabfoodMenu_mutations from "../grabfoodMenu/mutations.js";
import type * as grabfoodMenu_queries from "../grabfoodMenu/queries.js";
import type * as grabfoodOrders_mutations from "../grabfoodOrders/mutations.js";
import type * as grabfoodOrders_queries from "../grabfoodOrders/queries.js";
import type * as http from "../http.js";
import type * as ingredients_mutations from "../ingredients/mutations.js";
import type * as ingredients_queries from "../ingredients/queries.js";
import type * as integrations__shared_channelAdapter from "../integrations/_shared/channelAdapter.js";
import type * as integrations__shared_channelSaleEvent from "../integrations/_shared/channelSaleEvent.js";
import type * as integrations_bigseller_adapter from "../integrations/bigseller/adapter.js";
import type * as integrations_bigseller_config from "../integrations/bigseller/config.js";
import type * as integrations_bigseller_cron from "../integrations/bigseller/cron.js";
import type * as integrations_bigseller_helpers from "../integrations/bigseller/helpers.js";
import type * as integrations_bigseller_mutations from "../integrations/bigseller/mutations.js";
import type * as integrations_bigseller_queries from "../integrations/bigseller/queries.js";
import type * as integrations_bigseller_sync from "../integrations/bigseller/sync.js";
import type * as integrations_gobiz_adapter from "../integrations/gobiz/adapter.js";
import type * as integrations_gobiz_config from "../integrations/gobiz/config.js";
import type * as integrations_gobiz_helpers from "../integrations/gobiz/helpers.js";
import type * as integrations_gobiz_mutations from "../integrations/gobiz/mutations.js";
import type * as integrations_gobiz_testProbe from "../integrations/gobiz/testProbe.js";
import type * as integrations_grabfood_adapter from "../integrations/grabfood/adapter.js";
import type * as integrations_grabfood_config from "../integrations/grabfood/config.js";
import type * as integrations_grabfood_webhooks from "../integrations/grabfood/webhooks.js";
import type * as integrations_internal_adapter from "../integrations/internal/adapter.js";
import type * as integrations_internal_config from "../integrations/internal/config.js";
import type * as integrations_internal_queries from "../integrations/internal/queries.js";
import type * as integrations_k3mart_adapter from "../integrations/k3mart/adapter.js";
import type * as integrations_k3mart_config from "../integrations/k3mart/config.js";
import type * as integrations_k3mart_helpers from "../integrations/k3mart/helpers.js";
import type * as integrations_k3mart_queries from "../integrations/k3mart/queries.js";
import type * as integrations_pos___tests___fixtures from "../integrations/pos/__tests__/fixtures.js";
import type * as integrations_pos_adapter from "../integrations/pos/adapter.js";
import type * as integrations_pos_checkpoint from "../integrations/pos/checkpoint.js";
import type * as integrations_pos_contractSchema from "../integrations/pos/contractSchema.js";
import type * as integrations_pos_recordBuilders from "../integrations/pos/recordBuilders.js";
import type * as integrations_pos_sync from "../integrations/pos/sync.js";
import type * as integrations_pos_types from "../integrations/pos/types.js";
import type * as integrations_qris_provider from "../integrations/qris/provider.js";
import type * as integrations_qris_webhooks from "../integrations/qris/webhooks.js";
import type * as integrations_qris_xendit from "../integrations/qris/xendit.js";
import type * as integrations_registry from "../integrations/registry.js";
import type * as integrityChecks_mutations from "../integrityChecks/mutations.js";
import type * as integrityChecks_queries from "../integrityChecks/queries.js";
import type * as inventory_fifo from "../inventory/fifo.js";
import type * as inventory_helpers from "../inventory/helpers.js";
import type * as inventory_mutations from "../inventory/mutations.js";
import type * as inventory_queries from "../inventory/queries.js";
import type * as invoices_mutations from "../invoices/mutations.js";
import type * as invoices_queries from "../invoices/queries.js";
import type * as journalImport_mutations from "../journalImport/mutations.js";
import type * as k3martCockpit_helpers from "../k3martCockpit/helpers.js";
import type * as k3martCockpit_mutations from "../k3martCockpit/mutations.js";
import type * as k3martCockpit_queries from "../k3martCockpit/queries.js";
import type * as k3martCockpit_queryHelpers_dispatchHelpers from "../k3martCockpit/queryHelpers/dispatchHelpers.js";
import type * as k3martCockpit_queryHelpers_stockHelpers from "../k3martCockpit/queryHelpers/stockHelpers.js";
import type * as k3martKitchen_queries from "../k3martKitchen/queries.js";
import type * as kitchenComponents_mutations from "../kitchenComponents/mutations.js";
import type * as kitchenComponents_queries from "../kitchenComponents/queries.js";
import type * as kitchenConfig_mutations from "../kitchenConfig/mutations.js";
import type * as kitchenConfig_queries from "../kitchenConfig/queries.js";
import type * as kitchenDailyOverrides_mutations from "../kitchenDailyOverrides/mutations.js";
import type * as kitchenShiftRecords_ingredientDeduction from "../kitchenShiftRecords/ingredientDeduction.js";
import type * as kitchenShiftRecords_mutations from "../kitchenShiftRecords/mutations.js";
import type * as kitchenShiftRecords_queries from "../kitchenShiftRecords/queries.js";
import type * as lib_accountUtils from "../lib/accountUtils.js";
import type * as lib_auth from "../lib/auth.js";
import type * as lib_componentUnit from "../lib/componentUnit.js";
import type * as lib_confidence from "../lib/confidence.js";
import type * as lib_costCalculator from "../lib/costCalculator.js";
import type * as lib_costInvalidation from "../lib/costInvalidation.js";
import type * as lib_counter from "../lib/counter.js";
import type * as lib_externalSource from "../lib/externalSource.js";
import type * as lib_functions from "../lib/functions.js";
import type * as lib_fuzzyMatch from "../lib/fuzzyMatch.js";
import type * as lib_hierarchyTraversal from "../lib/hierarchyTraversal.js";
import type * as lib_indonesianDate from "../lib/indonesianDate.js";
import type * as lib_journalEngine from "../lib/journalEngine.js";
import type * as lib_journalHelpers from "../lib/journalHelpers.js";
import type * as lib_jwt from "../lib/jwt.js";
import type * as lib_periodBuckets from "../lib/periodBuckets.js";
import type * as lib_periodRange from "../lib/periodRange.js";
import type * as lib_queryHelpers from "../lib/queryHelpers.js";
import type * as lib_stockDelta from "../lib/stockDelta.js";
import type * as lib_telegramHtml from "../lib/telegramHtml.js";
import type * as lib_transientError from "../lib/transientError.js";
import type * as lib_validation from "../lib/validation.js";
import type * as manualJournal_mutations from "../manualJournal/mutations.js";
import type * as manualJournal_queries from "../manualJournal/queries.js";
import type * as materials_mutations from "../materials/mutations.js";
import type * as materials_queries from "../materials/queries.js";
import type * as menuProductComponents_mutations from "../menuProductComponents/mutations.js";
import type * as menuProductComponents_queries from "../menuProductComponents/queries.js";
import type * as menuProducts_mutations from "../menuProducts/mutations.js";
import type * as menuProducts_queries from "../menuProducts/queries.js";
import type * as migrations_bigsellerFeeSignFix from "../migrations/bigsellerFeeSignFix.js";
import type * as migrations_bigsellerRevenueBackfill from "../migrations/bigsellerRevenueBackfill.js";
import type * as migrations_bomBackfill from "../migrations/bomBackfill.js";
import type * as migrations_bomRefactorV2 from "../migrations/bomRefactorV2.js";
import type * as migrations_bomVerification from "../migrations/bomVerification.js";
import type * as migrations_categorySimplification from "../migrations/categorySimplification.js";
import type * as migrations_channelRoutingSeed from "../migrations/channelRoutingSeed.js";
import type * as migrations_consignmentRecognitionDate from "../migrations/consignmentRecognitionDate.js";
import type * as migrations_fixConfirmedOrders from "../migrations/fixConfirmedOrders.js";
import type * as migrations_fixDispatchPlanOutlets from "../migrations/fixDispatchPlanOutlets.js";
import type * as migrations_gobizCleanupLegacySummaries from "../migrations/gobizCleanupLegacySummaries.js";
import type * as migrations_gofoodSaleToChannelSale from "../migrations/gofoodSaleToChannelSale.js";
import type * as migrations_inventorySetup from "../migrations/inventorySetup.js";
import type * as migrations_posPurgeTestRows from "../migrations/posPurgeTestRows.js";
import type * as migrations_restoreCapexReimbursements from "../migrations/restoreCapexReimbursements.js";
import type * as migrations_schemaCleanup from "../migrations/schemaCleanup.js";
import type * as migrations_seedFinishedGoodsLocations from "../migrations/seedFinishedGoodsLocations.js";
import type * as orders_deleteAll from "../orders/deleteAll.js";
import type * as orders_helpers from "../orders/helpers.js";
import type * as orders_helpers_autoEntry from "../orders/helpers/autoEntry.js";
import type * as orders_helpers_ballDistribution from "../orders/helpers/ballDistribution.js";
import type * as orders_helpers_batchFetching from "../orders/helpers/batchFetching.js";
import type * as orders_helpers_customerResolution from "../orders/helpers/customerResolution.js";
import type * as orders_helpers_index from "../orders/helpers/index.js";
import type * as orders_helpers_insertOrder from "../orders/helpers/insertOrder.js";
import type * as orders_helpers_kanbanBuilders from "../orders/helpers/kanbanBuilders.js";
import type * as orders_helpers_kitchenEnrichment from "../orders/helpers/kitchenEnrichment.js";
import type * as orders_helpers_orderItemProcessing from "../orders/helpers/orderItemProcessing.js";
import type * as orders_helpers_productionRecords from "../orders/helpers/productionRecords.js";
import type * as orders_helpers_statusFetching from "../orders/helpers/statusFetching.js";
import type * as orders_helpers_statusTransitions from "../orders/helpers/statusTransitions.js";
import type * as orders_helpers_usageTracking from "../orders/helpers/usageTracking.js";
import type * as orders_helpers_voucherHandling from "../orders/helpers/voucherHandling.js";
import type * as orders_kitchenQueries from "../orders/kitchenQueries.js";
import type * as orders_migrations from "../orders/migrations.js";
import type * as orders_mutations_index from "../orders/mutations/index.js";
import type * as orders_mutations_inventoryIntegration from "../orders/mutations/inventoryIntegration.js";
import type * as orders_mutations_itemCrud from "../orders/mutations/itemCrud.js";
import type * as orders_mutations_kitchen from "../orders/mutations/kitchen.js";
import type * as orders_mutations_migrations from "../orders/mutations/migrations.js";
import type * as orders_mutations_orderCrud from "../orders/mutations/orderCrud.js";
import type * as orders_mutations_packaging from "../orders/mutations/packaging.js";
import type * as orders_mutations_statusUpdates from "../orders/mutations/statusUpdates.js";
import type * as orders_queries from "../orders/queries.js";
import type * as orders_types from "../orders/types.js";
import type * as orders_validators from "../orders/validators.js";
import type * as orders_whatsapp from "../orders/whatsapp.js";
import type * as orders_whatsappHelpers from "../orders/whatsappHelpers.js";
import type * as payroll_helpers from "../payroll/helpers.js";
import type * as payroll_mutations from "../payroll/mutations.js";
import type * as payroll_queries from "../payroll/queries.js";
import type * as platformCredentials_actions from "../platformCredentials/actions.js";
import type * as platformCredentials_mutations from "../platformCredentials/mutations.js";
import type * as platformCredentials_queries from "../platformCredentials/queries.js";
import type * as productInventory_backfill from "../productInventory/backfill.js";
import type * as productInventory_channelAudit from "../productInventory/channelAudit.js";
import type * as productInventory_channelAuditMutations from "../productInventory/channelAuditMutations.js";
import type * as productInventory_channelFlags from "../productInventory/channelFlags.js";
import type * as productInventory_channelRouting from "../productInventory/channelRouting.js";
import type * as productInventory_channelRoutingQueries from "../productInventory/channelRoutingQueries.js";
import type * as productInventory_channelSale from "../productInventory/channelSale.js";
import type * as productInventory_depotAutoSeed from "../productInventory/depotAutoSeed.js";
import type * as productInventory_mutations from "../productInventory/mutations.js";
import type * as productInventory_queries from "../productInventory/queries.js";
import type * as productInventory_stockTracker from "../productInventory/stockTracker.js";
import type * as productInventory_substitution from "../productInventory/substitution.js";
import type * as productionCounts_mutations from "../productionCounts/mutations.js";
import type * as productionCounts_queries from "../productionCounts/queries.js";
import type * as productionLog_helpers from "../productionLog/helpers.js";
import type * as productionLog_queries from "../productionLog/queries.js";
import type * as productionRecipes_mutations from "../productionRecipes/mutations.js";
import type * as productionRecipes_queries from "../productionRecipes/queries.js";
import type * as productionTargets_mutations from "../productionTargets/mutations.js";
import type * as productionTargets_queries from "../productionTargets/queries.js";
import type * as productionUnitTypes_mutations from "../productionUnitTypes/mutations.js";
import type * as productionUnitTypes_queries from "../productionUnitTypes/queries.js";
import type * as qrisPayments___tests____factory from "../qrisPayments/__tests__/_factory.js";
import type * as qrisPayments_actions from "../qrisPayments/actions.js";
import type * as qrisPayments_mutations from "../qrisPayments/mutations.js";
import type * as qrisPayments_queries from "../qrisPayments/queries.js";
import type * as reimbursements_helpers from "../reimbursements/helpers.js";
import type * as reimbursements_mutations from "../reimbursements/mutations.js";
import type * as reimbursements_queries from "../reimbursements/queries.js";
import type * as reports_dailySales from "../reports/dailySales.js";
import type * as reports_financialExport from "../reports/financialExport.js";
import type * as reports_incomeStatement from "../reports/incomeStatement.js";
import type * as reports_platform from "../reports/platform.js";
import type * as reports_productionUnitHelpers from "../reports/productionUnitHelpers.js";
import type * as reports_revenueHelpers from "../reports/revenueHelpers.js";
import type * as reports_unitEconomics from "../reports/unitEconomics.js";
import type * as restock_mutations from "../restock/mutations.js";
import type * as restock_queries from "../restock/queries.js";
import type * as shipping_mutations from "../shipping/mutations.js";
import type * as shipping_queries from "../shipping/queries.js";
import type * as staffAttendance___tests___helpers from "../staffAttendance/__tests__/helpers.js";
import type * as staffAttendance_aggregation from "../staffAttendance/aggregation.js";
import type * as staffAttendance_constants from "../staffAttendance/constants.js";
import type * as staffAttendance_flagEngine from "../staffAttendance/flagEngine.js";
import type * as staffAttendance_mutations from "../staffAttendance/mutations.js";
import type * as staffAttendance_queries from "../staffAttendance/queries.js";
import type * as storageLocations_mutations from "../storageLocations/mutations.js";
import type * as storageLocations_queries from "../storageLocations/queries.js";
import type * as subscriptions_creditMath from "../subscriptions/creditMath.js";
import type * as subscriptions_invoicing from "../subscriptions/invoicing.js";
import type * as subscriptions_ledger from "../subscriptions/ledger.js";
import type * as subscriptions_mutations from "../subscriptions/mutations.js";
import type * as subscriptions_outOfCredit from "../subscriptions/outOfCredit.js";
import type * as subscriptions_queries from "../subscriptions/queries.js";
import type * as subscriptions_recognition from "../subscriptions/recognition.js";
import type * as subscriptions_reconcile from "../subscriptions/reconcile.js";
import type * as subscriptions_reconcileMath from "../subscriptions/reconcileMath.js";
import type * as subscriptions_revenueGate from "../subscriptions/revenueGate.js";
import type * as subscriptions_rollover from "../subscriptions/rollover.js";
import type * as subscriptions_scheduleLine from "../subscriptions/scheduleLine.js";
import type * as subscriptions_scheduling_confirmWeek from "../subscriptions/scheduling/confirmWeek.js";
import type * as subscriptions_types from "../subscriptions/types.js";
import type * as subscriptions_weekBounds from "../subscriptions/weekBounds.js";
import type * as subscriptions_weeks from "../subscriptions/weeks.js";
import type * as telegram___tests___testHelpers from "../telegram/__tests__/testHelpers.js";
import type * as telegram_chatRegistry from "../telegram/chatRegistry.js";
import type * as telegram_config from "../telegram/config.js";
import type * as telegram_cronRetry from "../telegram/cronRetry.js";
import type * as telegram_deliveryReceipts from "../telegram/deliveryReceipts.js";
import type * as telegram_packListFormat from "../telegram/packListFormat.js";
import type * as telegram_queries_dueClassification from "../telegram/queries/dueClassification.js";
import type * as telegram_queries_packListQuery from "../telegram/queries/packListQuery.js";
import type * as telegram_salesSummary_range from "../telegram/salesSummary/range.js";
import type * as telegram_salesSummary_salesSummaryFormat from "../telegram/salesSummary/salesSummaryFormat.js";
import type * as telegram_salesSummary_salesSummaryQuery from "../telegram/salesSummary/salesSummaryQuery.js";
import type * as telegram_salesSummary_sendSalesSummary from "../telegram/salesSummary/sendSalesSummary.js";
import type * as telegram_sendPackList from "../telegram/sendPackList.js";
import type * as telegram_webhook from "../telegram/webhook.js";
import type * as vouchers_mutations from "../vouchers/mutations.js";
import type * as vouchers_queries from "../vouchers/queries.js";
import type * as whatsappTemplates_mutations from "../whatsappTemplates/mutations.js";
import type * as whatsappTemplates_queries from "../whatsappTemplates/queries.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  "accounts/mutations": typeof accounts_mutations;
  "accounts/queries": typeof accounts_queries;
  "auth/mutations": typeof auth_mutations;
  "auth/queries": typeof auth_queries;
  "auth/seed": typeof auth_seed;
  "bankAccounts/mutations": typeof bankAccounts_mutations;
  "bankAccounts/queries": typeof bankAccounts_queries;
  "bankKeywordRules/defaultRules": typeof bankKeywordRules_defaultRules;
  "bankKeywordRules/mutations": typeof bankKeywordRules_mutations;
  "bankKeywordRules/queries": typeof bankKeywordRules_queries;
  "bankStatements/__tests__/reconcileHelpers": typeof bankStatements___tests___reconcileHelpers;
  "bankStatements/channelMapping": typeof bankStatements_channelMapping;
  "bankStatements/matchEngine": typeof bankStatements_matchEngine;
  "bankStatements/mutations": typeof bankStatements_mutations;
  "bankStatements/queries": typeof bankStatements_queries;
  "bigsellerOrders/actions": typeof bigsellerOrders_actions;
  "bigsellerOrders/mutations": typeof bigsellerOrders_mutations;
  "bigsellerOrders/queries": typeof bigsellerOrders_queries;
  "businessSettings/mutations": typeof businessSettings_mutations;
  "businessSettings/queries": typeof businessSettings_queries;
  "channels/mutations": typeof channels_mutations;
  "channels/queries": typeof channels_queries;
  "componentTypes/dedupe": typeof componentTypes_dedupe;
  "componentTypes/helpers": typeof componentTypes_helpers;
  "componentTypes/mutations": typeof componentTypes_mutations;
  "componentTypes/queries": typeof componentTypes_queries;
  "componentTypes/seed": typeof componentTypes_seed;
  "consignment/helpers": typeof consignment_helpers;
  "consignment/mutations": typeof consignment_mutations;
  "consignment/queries": typeof consignment_queries;
  crons: typeof crons;
  "customers/mutations": typeof customers_mutations;
  "customers/queries": typeof customers_queries;
  "dispatchPlanner/helpers": typeof dispatchPlanner_helpers;
  "dispatchPlanner/helpers/index": typeof dispatchPlanner_helpers_index;
  "dispatchPlanner/helpers/inventorySimulation": typeof dispatchPlanner_helpers_inventorySimulation;
  "dispatchPlanner/helpers/weeklyPlanBuilder": typeof dispatchPlanner_helpers_weeklyPlanBuilder;
  "dispatchPlanner/mutations": typeof dispatchPlanner_mutations;
  "dispatchPlanner/queries": typeof dispatchPlanner_queries;
  "dispatchPlanner/types": typeof dispatchPlanner_types;
  "expenses/analyticsQueries": typeof expenses_analyticsQueries;
  "expenses/auditTrail": typeof expenses_auditTrail;
  "expenses/bulkMutations": typeof expenses_bulkMutations;
  "expenses/constants": typeof expenses_constants;
  "expenses/fraudHelpers": typeof expenses_fraudHelpers;
  "expenses/helpers": typeof expenses_helpers;
  "expenses/mutations": typeof expenses_mutations;
  "expenses/queries": typeof expenses_queries;
  "externalData/actions": typeof externalData_actions;
  "externalData/helpers/dashboardHelpers": typeof externalData_helpers_dashboardHelpers;
  "externalData/helpers/lifetimeHelpers": typeof externalData_helpers_lifetimeHelpers;
  "externalData/helpers/restockHelpers": typeof externalData_helpers_restockHelpers;
  "externalData/helpers/revenueItemsHelpers": typeof externalData_helpers_revenueItemsHelpers;
  "externalData/helpers/sellThroughHelpers": typeof externalData_helpers_sellThroughHelpers;
  "externalData/helpers/timeSeriesHelpers": typeof externalData_helpers_timeSeriesHelpers;
  "externalData/mutations": typeof externalData_mutations;
  "externalData/queries": typeof externalData_queries;
  "feedback/mutations": typeof feedback_mutations;
  "feedback/queries": typeof feedback_queries;
  "fixedAssets/helpers": typeof fixedAssets_helpers;
  "fixedAssets/mutations": typeof fixedAssets_mutations;
  "fixedAssets/queries": typeof fixedAssets_queries;
  "gofoodDepot/helpers": typeof gofoodDepot_helpers;
  "gofoodDepot/mutations": typeof gofoodDepot_mutations;
  "gofoodDepot/queries": typeof gofoodDepot_queries;
  "grabfoodMenu/mutations": typeof grabfoodMenu_mutations;
  "grabfoodMenu/queries": typeof grabfoodMenu_queries;
  "grabfoodOrders/mutations": typeof grabfoodOrders_mutations;
  "grabfoodOrders/queries": typeof grabfoodOrders_queries;
  http: typeof http;
  "ingredients/mutations": typeof ingredients_mutations;
  "ingredients/queries": typeof ingredients_queries;
  "integrations/_shared/channelAdapter": typeof integrations__shared_channelAdapter;
  "integrations/_shared/channelSaleEvent": typeof integrations__shared_channelSaleEvent;
  "integrations/bigseller/adapter": typeof integrations_bigseller_adapter;
  "integrations/bigseller/config": typeof integrations_bigseller_config;
  "integrations/bigseller/cron": typeof integrations_bigseller_cron;
  "integrations/bigseller/helpers": typeof integrations_bigseller_helpers;
  "integrations/bigseller/mutations": typeof integrations_bigseller_mutations;
  "integrations/bigseller/queries": typeof integrations_bigseller_queries;
  "integrations/bigseller/sync": typeof integrations_bigseller_sync;
  "integrations/gobiz/adapter": typeof integrations_gobiz_adapter;
  "integrations/gobiz/config": typeof integrations_gobiz_config;
  "integrations/gobiz/helpers": typeof integrations_gobiz_helpers;
  "integrations/gobiz/mutations": typeof integrations_gobiz_mutations;
  "integrations/gobiz/testProbe": typeof integrations_gobiz_testProbe;
  "integrations/grabfood/adapter": typeof integrations_grabfood_adapter;
  "integrations/grabfood/config": typeof integrations_grabfood_config;
  "integrations/grabfood/webhooks": typeof integrations_grabfood_webhooks;
  "integrations/internal/adapter": typeof integrations_internal_adapter;
  "integrations/internal/config": typeof integrations_internal_config;
  "integrations/internal/queries": typeof integrations_internal_queries;
  "integrations/k3mart/adapter": typeof integrations_k3mart_adapter;
  "integrations/k3mart/config": typeof integrations_k3mart_config;
  "integrations/k3mart/helpers": typeof integrations_k3mart_helpers;
  "integrations/k3mart/queries": typeof integrations_k3mart_queries;
  "integrations/pos/__tests__/fixtures": typeof integrations_pos___tests___fixtures;
  "integrations/pos/adapter": typeof integrations_pos_adapter;
  "integrations/pos/checkpoint": typeof integrations_pos_checkpoint;
  "integrations/pos/contractSchema": typeof integrations_pos_contractSchema;
  "integrations/pos/recordBuilders": typeof integrations_pos_recordBuilders;
  "integrations/pos/sync": typeof integrations_pos_sync;
  "integrations/pos/types": typeof integrations_pos_types;
  "integrations/qris/provider": typeof integrations_qris_provider;
  "integrations/qris/webhooks": typeof integrations_qris_webhooks;
  "integrations/qris/xendit": typeof integrations_qris_xendit;
  "integrations/registry": typeof integrations_registry;
  "integrityChecks/mutations": typeof integrityChecks_mutations;
  "integrityChecks/queries": typeof integrityChecks_queries;
  "inventory/fifo": typeof inventory_fifo;
  "inventory/helpers": typeof inventory_helpers;
  "inventory/mutations": typeof inventory_mutations;
  "inventory/queries": typeof inventory_queries;
  "invoices/mutations": typeof invoices_mutations;
  "invoices/queries": typeof invoices_queries;
  "journalImport/mutations": typeof journalImport_mutations;
  "k3martCockpit/helpers": typeof k3martCockpit_helpers;
  "k3martCockpit/mutations": typeof k3martCockpit_mutations;
  "k3martCockpit/queries": typeof k3martCockpit_queries;
  "k3martCockpit/queryHelpers/dispatchHelpers": typeof k3martCockpit_queryHelpers_dispatchHelpers;
  "k3martCockpit/queryHelpers/stockHelpers": typeof k3martCockpit_queryHelpers_stockHelpers;
  "k3martKitchen/queries": typeof k3martKitchen_queries;
  "kitchenComponents/mutations": typeof kitchenComponents_mutations;
  "kitchenComponents/queries": typeof kitchenComponents_queries;
  "kitchenConfig/mutations": typeof kitchenConfig_mutations;
  "kitchenConfig/queries": typeof kitchenConfig_queries;
  "kitchenDailyOverrides/mutations": typeof kitchenDailyOverrides_mutations;
  "kitchenShiftRecords/ingredientDeduction": typeof kitchenShiftRecords_ingredientDeduction;
  "kitchenShiftRecords/mutations": typeof kitchenShiftRecords_mutations;
  "kitchenShiftRecords/queries": typeof kitchenShiftRecords_queries;
  "lib/accountUtils": typeof lib_accountUtils;
  "lib/auth": typeof lib_auth;
  "lib/componentUnit": typeof lib_componentUnit;
  "lib/confidence": typeof lib_confidence;
  "lib/costCalculator": typeof lib_costCalculator;
  "lib/costInvalidation": typeof lib_costInvalidation;
  "lib/counter": typeof lib_counter;
  "lib/externalSource": typeof lib_externalSource;
  "lib/functions": typeof lib_functions;
  "lib/fuzzyMatch": typeof lib_fuzzyMatch;
  "lib/hierarchyTraversal": typeof lib_hierarchyTraversal;
  "lib/indonesianDate": typeof lib_indonesianDate;
  "lib/journalEngine": typeof lib_journalEngine;
  "lib/journalHelpers": typeof lib_journalHelpers;
  "lib/jwt": typeof lib_jwt;
  "lib/periodBuckets": typeof lib_periodBuckets;
  "lib/periodRange": typeof lib_periodRange;
  "lib/queryHelpers": typeof lib_queryHelpers;
  "lib/stockDelta": typeof lib_stockDelta;
  "lib/telegramHtml": typeof lib_telegramHtml;
  "lib/transientError": typeof lib_transientError;
  "lib/validation": typeof lib_validation;
  "manualJournal/mutations": typeof manualJournal_mutations;
  "manualJournal/queries": typeof manualJournal_queries;
  "materials/mutations": typeof materials_mutations;
  "materials/queries": typeof materials_queries;
  "menuProductComponents/mutations": typeof menuProductComponents_mutations;
  "menuProductComponents/queries": typeof menuProductComponents_queries;
  "menuProducts/mutations": typeof menuProducts_mutations;
  "menuProducts/queries": typeof menuProducts_queries;
  "migrations/bigsellerFeeSignFix": typeof migrations_bigsellerFeeSignFix;
  "migrations/bigsellerRevenueBackfill": typeof migrations_bigsellerRevenueBackfill;
  "migrations/bomBackfill": typeof migrations_bomBackfill;
  "migrations/bomRefactorV2": typeof migrations_bomRefactorV2;
  "migrations/bomVerification": typeof migrations_bomVerification;
  "migrations/categorySimplification": typeof migrations_categorySimplification;
  "migrations/channelRoutingSeed": typeof migrations_channelRoutingSeed;
  "migrations/consignmentRecognitionDate": typeof migrations_consignmentRecognitionDate;
  "migrations/fixConfirmedOrders": typeof migrations_fixConfirmedOrders;
  "migrations/fixDispatchPlanOutlets": typeof migrations_fixDispatchPlanOutlets;
  "migrations/gobizCleanupLegacySummaries": typeof migrations_gobizCleanupLegacySummaries;
  "migrations/gofoodSaleToChannelSale": typeof migrations_gofoodSaleToChannelSale;
  "migrations/inventorySetup": typeof migrations_inventorySetup;
  "migrations/posPurgeTestRows": typeof migrations_posPurgeTestRows;
  "migrations/restoreCapexReimbursements": typeof migrations_restoreCapexReimbursements;
  "migrations/schemaCleanup": typeof migrations_schemaCleanup;
  "migrations/seedFinishedGoodsLocations": typeof migrations_seedFinishedGoodsLocations;
  "orders/deleteAll": typeof orders_deleteAll;
  "orders/helpers": typeof orders_helpers;
  "orders/helpers/autoEntry": typeof orders_helpers_autoEntry;
  "orders/helpers/ballDistribution": typeof orders_helpers_ballDistribution;
  "orders/helpers/batchFetching": typeof orders_helpers_batchFetching;
  "orders/helpers/customerResolution": typeof orders_helpers_customerResolution;
  "orders/helpers/index": typeof orders_helpers_index;
  "orders/helpers/insertOrder": typeof orders_helpers_insertOrder;
  "orders/helpers/kanbanBuilders": typeof orders_helpers_kanbanBuilders;
  "orders/helpers/kitchenEnrichment": typeof orders_helpers_kitchenEnrichment;
  "orders/helpers/orderItemProcessing": typeof orders_helpers_orderItemProcessing;
  "orders/helpers/productionRecords": typeof orders_helpers_productionRecords;
  "orders/helpers/statusFetching": typeof orders_helpers_statusFetching;
  "orders/helpers/statusTransitions": typeof orders_helpers_statusTransitions;
  "orders/helpers/usageTracking": typeof orders_helpers_usageTracking;
  "orders/helpers/voucherHandling": typeof orders_helpers_voucherHandling;
  "orders/kitchenQueries": typeof orders_kitchenQueries;
  "orders/migrations": typeof orders_migrations;
  "orders/mutations/index": typeof orders_mutations_index;
  "orders/mutations/inventoryIntegration": typeof orders_mutations_inventoryIntegration;
  "orders/mutations/itemCrud": typeof orders_mutations_itemCrud;
  "orders/mutations/kitchen": typeof orders_mutations_kitchen;
  "orders/mutations/migrations": typeof orders_mutations_migrations;
  "orders/mutations/orderCrud": typeof orders_mutations_orderCrud;
  "orders/mutations/packaging": typeof orders_mutations_packaging;
  "orders/mutations/statusUpdates": typeof orders_mutations_statusUpdates;
  "orders/queries": typeof orders_queries;
  "orders/types": typeof orders_types;
  "orders/validators": typeof orders_validators;
  "orders/whatsapp": typeof orders_whatsapp;
  "orders/whatsappHelpers": typeof orders_whatsappHelpers;
  "payroll/helpers": typeof payroll_helpers;
  "payroll/mutations": typeof payroll_mutations;
  "payroll/queries": typeof payroll_queries;
  "platformCredentials/actions": typeof platformCredentials_actions;
  "platformCredentials/mutations": typeof platformCredentials_mutations;
  "platformCredentials/queries": typeof platformCredentials_queries;
  "productInventory/backfill": typeof productInventory_backfill;
  "productInventory/channelAudit": typeof productInventory_channelAudit;
  "productInventory/channelAuditMutations": typeof productInventory_channelAuditMutations;
  "productInventory/channelFlags": typeof productInventory_channelFlags;
  "productInventory/channelRouting": typeof productInventory_channelRouting;
  "productInventory/channelRoutingQueries": typeof productInventory_channelRoutingQueries;
  "productInventory/channelSale": typeof productInventory_channelSale;
  "productInventory/depotAutoSeed": typeof productInventory_depotAutoSeed;
  "productInventory/mutations": typeof productInventory_mutations;
  "productInventory/queries": typeof productInventory_queries;
  "productInventory/stockTracker": typeof productInventory_stockTracker;
  "productInventory/substitution": typeof productInventory_substitution;
  "productionCounts/mutations": typeof productionCounts_mutations;
  "productionCounts/queries": typeof productionCounts_queries;
  "productionLog/helpers": typeof productionLog_helpers;
  "productionLog/queries": typeof productionLog_queries;
  "productionRecipes/mutations": typeof productionRecipes_mutations;
  "productionRecipes/queries": typeof productionRecipes_queries;
  "productionTargets/mutations": typeof productionTargets_mutations;
  "productionTargets/queries": typeof productionTargets_queries;
  "productionUnitTypes/mutations": typeof productionUnitTypes_mutations;
  "productionUnitTypes/queries": typeof productionUnitTypes_queries;
  "qrisPayments/__tests__/_factory": typeof qrisPayments___tests____factory;
  "qrisPayments/actions": typeof qrisPayments_actions;
  "qrisPayments/mutations": typeof qrisPayments_mutations;
  "qrisPayments/queries": typeof qrisPayments_queries;
  "reimbursements/helpers": typeof reimbursements_helpers;
  "reimbursements/mutations": typeof reimbursements_mutations;
  "reimbursements/queries": typeof reimbursements_queries;
  "reports/dailySales": typeof reports_dailySales;
  "reports/financialExport": typeof reports_financialExport;
  "reports/incomeStatement": typeof reports_incomeStatement;
  "reports/platform": typeof reports_platform;
  "reports/productionUnitHelpers": typeof reports_productionUnitHelpers;
  "reports/revenueHelpers": typeof reports_revenueHelpers;
  "reports/unitEconomics": typeof reports_unitEconomics;
  "restock/mutations": typeof restock_mutations;
  "restock/queries": typeof restock_queries;
  "shipping/mutations": typeof shipping_mutations;
  "shipping/queries": typeof shipping_queries;
  "staffAttendance/__tests__/helpers": typeof staffAttendance___tests___helpers;
  "staffAttendance/aggregation": typeof staffAttendance_aggregation;
  "staffAttendance/constants": typeof staffAttendance_constants;
  "staffAttendance/flagEngine": typeof staffAttendance_flagEngine;
  "staffAttendance/mutations": typeof staffAttendance_mutations;
  "staffAttendance/queries": typeof staffAttendance_queries;
  "storageLocations/mutations": typeof storageLocations_mutations;
  "storageLocations/queries": typeof storageLocations_queries;
  "subscriptions/creditMath": typeof subscriptions_creditMath;
  "subscriptions/invoicing": typeof subscriptions_invoicing;
  "subscriptions/ledger": typeof subscriptions_ledger;
  "subscriptions/mutations": typeof subscriptions_mutations;
  "subscriptions/outOfCredit": typeof subscriptions_outOfCredit;
  "subscriptions/queries": typeof subscriptions_queries;
  "subscriptions/recognition": typeof subscriptions_recognition;
  "subscriptions/reconcile": typeof subscriptions_reconcile;
  "subscriptions/reconcileMath": typeof subscriptions_reconcileMath;
  "subscriptions/revenueGate": typeof subscriptions_revenueGate;
  "subscriptions/rollover": typeof subscriptions_rollover;
  "subscriptions/scheduleLine": typeof subscriptions_scheduleLine;
  "subscriptions/scheduling/confirmWeek": typeof subscriptions_scheduling_confirmWeek;
  "subscriptions/types": typeof subscriptions_types;
  "subscriptions/weekBounds": typeof subscriptions_weekBounds;
  "subscriptions/weeks": typeof subscriptions_weeks;
  "telegram/__tests__/testHelpers": typeof telegram___tests___testHelpers;
  "telegram/chatRegistry": typeof telegram_chatRegistry;
  "telegram/config": typeof telegram_config;
  "telegram/cronRetry": typeof telegram_cronRetry;
  "telegram/deliveryReceipts": typeof telegram_deliveryReceipts;
  "telegram/packListFormat": typeof telegram_packListFormat;
  "telegram/queries/dueClassification": typeof telegram_queries_dueClassification;
  "telegram/queries/packListQuery": typeof telegram_queries_packListQuery;
  "telegram/salesSummary/range": typeof telegram_salesSummary_range;
  "telegram/salesSummary/salesSummaryFormat": typeof telegram_salesSummary_salesSummaryFormat;
  "telegram/salesSummary/salesSummaryQuery": typeof telegram_salesSummary_salesSummaryQuery;
  "telegram/salesSummary/sendSalesSummary": typeof telegram_salesSummary_sendSalesSummary;
  "telegram/sendPackList": typeof telegram_sendPackList;
  "telegram/webhook": typeof telegram_webhook;
  "vouchers/mutations": typeof vouchers_mutations;
  "vouchers/queries": typeof vouchers_queries;
  "whatsappTemplates/mutations": typeof whatsappTemplates_mutations;
  "whatsappTemplates/queries": typeof whatsappTemplates_queries;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
